# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7606d61161bee25e1d2f966765c9cb3143d3f0fd5985c2b22265bf4a97952a1eb212f47ad5ef62d5bb5063f6b9ee84894a1d22228b7296227d3cacafc6ad2370

test:
  secret_key_base: 913dfe4cea964587219b7eeb025c3818832840ee90a9e856f244c5f1c653fab33ebe254926658d0e9ae637466b91008ed43b7edbbb118947b5f1f2783e42b90c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
